### ISSUE TITLE
[FIXED] MeshLight, PointLight, SpotLight, AreaLight has bugs in BDPT integrator

### ISSUE THREAD

**Issue by odil24** [YafaRay/YafaRay-Blender#1]
[yafa351_scene.zip](https://github.com/YafaRay/YafaRay-Blender/files/4941379/yafa351_scene.zip)

**_Absolutly doesn't working when use:_**
- meshlight;
- pointlight;
- spotlight;
- arealight.

**Comment by DavidBluecame** [comment]
Hello, I'll look at this. I seems to work as in previous versions in Linux (not correctly, I believe, but that's why this integrator is considered unstable, because it does not really work as I would expect), I'll take a look at the Windows builds shortly to see if they are behaving worse for some reason.

**Comment by odil24** [comment]
Yes, in previous versions that integrator is worked except that Alpha-based
textures.

**Comment by odil24** [comment]
Hi. Any news in this issue?

**Comment by DavidBluecame** [comment]
Hello,

Are you sure this is a new issue in v3.5.1?  I've used v3.3.0 and the renders are similar...

If you could let me know which previous YafaRay version worked fine for you, I can try to find out what changed since.

**Comment by DavidBluecame** [comment]
This is in Windows 10 64bit, v3.5.1
![image](https://user-images.githubusercontent.com/3886025/89824545-93ffba00-db53-11ea-870a-4a5914f657f6.png)

**Comment by odil24** [comment]
:( it really strange I uninstalled Blender 2.79 and yafaray_v3 addon also and plus userpref.blend/startup.blend which is located on [users/user/appdata/roaming/blender foundation/2.79] and reinstall again. Now it works fine as normal :D
