### ISSUE TITLE
[Bug] IES light inside Spot lamp doesnt works

### ISSUE THREAD

**Issue by odil24** [YafaRay/YafaRay-Blender#2]
It doesnt work properly. Exactly, it is not showing IES profile rays and geometry also.

**Comment by DavidBluecame** [comment]
Hello. Please will you provide an example blend file showing the issue? Thanks.

**Comment by odil24** [comment]
Hello. I found the bug myself. It was been from IES file. I used another one and it works fine here now. ;)

Closed issue.
